### ISSUE TITLE
sink loading broken with version 2.9.0

### ISSUE THREAD

**Issue by matthiasglz** [osyris-project/osyris#100]
When trying to load an output with the new version 2.9.0 an Error is raised while loading the  #sinks

File /opt/anaconda3/lib/python3.8/site-packages/osyris/io/sink.py:59, in SinkReader.initialize(self, meta, units, select)
     57 sink = Datagroup()
     58 for i, (key, unit) in enumerate(zip(key_list, unit_list)):
---> 59     sink[key] = Array(values=sink_data[:, i] * unit.magnitude, unit=unit.units)
     60 utils.make_vector_arrays(sink, ndim=meta["ndim"])
     61 return sink

AttributeError: 'Unit' object has no attribute 'magnitude'

**Comment by nvaytet** [comment]
Can you paste the contents of your sink file? thanks

**Comment by nvaytet** [comment]
Did you make sure you deleted your config file before trying version 2.9?

**Comment by matthiasglz** [comment]
# Id,M,dmf,x,y,z,vx,vy,vz,rot_period,lx/|l|,ly/|l|,lz/|l|,acc_rate,acc_lum,age,int_lum,Teff
# 1,[M_sol],[M_sol],l,l,l,l t**-1,l t**-1,l t**-1,[year],1,1,1,[M_sol/year],[L_sol],[year],[L_sol],[K]
         1,    9.3610624050E-02,    0.0000000000E+00,    6.1551808770E-01,    7.3502595142E-01,    6.4746780895E-01,    2.5060240634E+01,    1.1221090701E+02,    1.8288385133E+02,    1.4022825485E+01,    1.8857921896E-01,    9.2498829811E-01,    3.2990078286E-01,    0.0000000000E+00,    0.0000000000E+00,    1.7275567625E+04,    7.1645396536E-02,    3.2071943735E+03
         2,    6.5267962484E-02,    0.0000000000E+00,    6.1423164022E-01,    7.3069135194E-01,    6.5489836175E-01,   -9.2704881807E+01,    3.8511665561E+01,    2.0275567256E+02,    4.4879806138E+00,   -7.3331880917E-01,   -2.2104662478E-02,    6.7952550211E-01,    0.0000000000E+00,    0.0000000000E+00,    1.5688153254E+04,    0.0000000000E+00,    0.0000000000E+00
         3,    6.4142497044E-02,    0.0000000000E+00,    6.1423162947E-01,    7.3069149509E-01,    6.5489813837E-01,   -2.6846091838E+01,   -8.5922903390E+01,    3.2216656085E+02,    4.4131551611E+00,   -7.2386054239E-01,   -2.4756505280E-02,    6.8950201640E-01,    0.0000000000E+00,    0.0000000000E+00,    1.5610894665E+04,    0.0000000000E+00,    0.0000000000E+00
         4,    6.5933847918E-02,    0.0000000000E+00,    6.1423171359E-01,    7.3069132078E-01,    6.5489834439E-01,   -7.9744157067E+01,    4.6573784677E+01,    1.4777515052E+02,    4.3881868155E+00,   -7.4647468650E-01,   -3.8240418384E-02,    6.6431409199E-01,    0.0000000000E+00,    0.0000000000E+00,    1.5276739438E+04,    0.0000000000E+00,    0.0000000000E+00
         5,    8.7616773288E-02,    0.0000000000E+00,    6.6706967225E-01,    9.4457366393E-01,    7.5093675679E-01,   -4.2801110270E+01,   -7.6605436420E+01,    2.3819406081E+02,    3.5175532327E+00,   -5.4258686136E-01,    6.6769136349E-01,   -5.0969377179E-01,    0.0000000000E+00,    0.0000000000E+00,    1.4155950356E+04,    3.6244310289E-02,    3.1298589634E+03
         6,    6.1467981324E-02,    0.0000000000E+00,    6.5028154204E-01,    9.5320080385E-01,    7.4785386984E-01,   -7.3598949113E+01,   -3.8635690835E+01,    2.1700550421E+02,    8.6592943795E+00,    3.9953137886E-02,   -4.9061666914E-01,   -8.7045909194E-01,    0.0000000000E+00,    0.0000000000E+00,    1.4003719161E+04,    0.0000000000E+00,    0.0000000000E+00
         7,    4.6201836790E-02,    0.0000000000E+00,    6.5028144278E-01,    9.5320065121E-01,    7.4785354235E-01,   -1.5385824961E+02,   -5.9312410420E+01,    2.4553149452E+02,    7.3472015465E+00,    3.8873168645E-02,   -4.3446439914E-01,   -8.9984974448E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3875655263E+04,    0.0000000000E+00,    0.0000000000E+00
         8,    2.1610363230E-02,    0.0000000000E+00,    6.5028130554E-01,    9.5320087677E-01,    7.4785390199E-01,   -1.1048348736E+02,   -1.2185708278E+01,    1.5340408895E+02,    5.4466435726E+00,    1.5027274776E-01,   -8.6368785942E-02,   -9.8486472883E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3741254624E+04,    0.0000000000E+00,    0.0000000000E+00
         9,    4.3424428158E-03,    0.0000000000E+00,    6.5028532292E-01,    9.5319388903E-01,    7.4785370969E-01,   -4.0424892965E+02,   -3.0712540827E+02,    3.8760397708E+02,    1.6873617241E+00,   -3.4693428775E-01,    5.0549342421E-01,   -7.9000822658E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3548573965E+04,    0.0000000000E+00,    0.0000000000E+00
        10,    3.9358519735E-03,    0.0000000000E+00,    6.5027981369E-01,    9.5319913367E-01,    7.4785250067E-01,   -6.0657688383E+02,   -1.9907524915E+01,    5.7086359988E+01,    1.5682135248E+00,   -2.8912136410E-01,    5.2951291057E-01,   -7.9751170171E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3411901794E+04,    0.0000000000E+00,    0.0000000000E+00
        11,    8.0773109230E-04,    0.0000000000E+00,    6.5123624273E-01,    9.5492555850E-01,    7.2205573817E-01,   -7.6134144680E+01,    3.7980750654E+01,    1.9252796465E+02,    3.4558127790E+01,    1.2303803264E-01,   -9.7491427322E-01,   -1.8548262018E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3410385875E+04,    0.0000000000E+00,    0.0000000000E+00
        12,    5.7473289257E-03,    0.0000000000E+00,    6.5028156039E-01,    9.5320138740E-01,    7.4785379112E-01,    5.9793659996E+02,    1.0722957818E+02,    4.1986501265E+02,    2.1463155183E+00,   -1.1574328972E-01,    5.8724008666E-01,   -8.0109460834E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3203836345E+04,    0.0000000000E+00,    0.0000000000E+00
        13,    9.7644957696E-04,    0.0000000000E+00,    6.5230345676E-01,    9.5166817653E-01,    7.4631515419E-01,   -9.9504178106E+01,   -3.4677327827E+01,    2.4613760700E+02,    1.2767445559E+02,   -2.2327134032E-01,    5.1994885553E-01,    8.2450172603E-01,    0.0000000000E+00,    0.0000000000E+00,    1.3050709023E+04,    0.0000000000E+00,    0.0000000000E+00
        14,    1.6092607280E-02,    0.0000000000E+00,    6.1262743346E-01,    7.2818061210E-01,    6.5531963694E-01,   -4.9069104141E+01,   -5.2611926195E+00,    2.0859692647E+02,    1.1438770883E+01,   -3.9608733218E-02,   -6.2419823094E-01,    7.8026131311E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2915466905E+04,    0.0000000000E+00,    0.0000000000E+00
        15,    1.5179831564E-02,    0.0000000000E+00,    6.1262739618E-01,    7.2818054067E-01,    6.5531956584E-01,   -5.7937947272E+01,    1.8596799435E+01,    1.6481763952E+02,    1.1313565663E+01,   -1.1074422515E-01,   -5.9624442022E-01,    7.9512785636E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2800865205E+04,    0.0000000000E+00,    0.0000000000E+00
        16,    1.4839644928E-02,    0.0000000000E+00,    6.1262741278E-01,    7.2818060959E-01,    6.5531949312E-01,   -5.1297916586E+01,   -4.9176322141E+01,    2.3164817300E+02,    1.0774682885E+01,   -7.7210414655E-02,   -6.0357518729E-01,    7.9355878494E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2717634664E+04,    0.0000000000E+00,    0.0000000000E+00
        17,    4.6766708521E-02,    0.0000000000E+00,    8.6886431227E-01,    8.0716344417E-01,    7.2661093544E-01,   -2.9915039071E+02,   -1.2906021560E+02,    1.5285267166E+02,    3.6600615177E+00,   -6.0717391384E-01,    5.8123072853E-01,    5.4176625824E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2414150063E+04,    0.0000000000E+00,    0.0000000000E+00
        18,    4.3302883383E-03,    0.0000000000E+00,    8.6917821389E-01,    8.1232190766E-01,    7.2627649944E-01,   -2.8745501284E+02,   -1.1229522074E+02,    1.4150052576E+02,    7.0221113615E+00,   -5.1007025652E-01,    5.0255525136E-01,    6.9804480711E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2400235292E+04,    0.0000000000E+00,    0.0000000000E+00
        19,    7.5569584563E-03,    0.0000000000E+00,    6.1262137311E-01,    7.2818532134E-01,    6.5529316915E-01,   -3.5830289727E+01,   -4.1152824051E+01,    2.7815906596E+02,    7.8344887099E+00,    5.2487362405E-01,   -5.5634431587E-01,    6.4419615101E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2183870403E+04,    0.0000000000E+00,    0.0000000000E+00
        20,    1.7344464876E-01,    1.0097497098E-05,    6.4952620822E-01,    6.9526651297E-01,    8.6349361135E-01,    0.0000000000E+00,    0.0000000000E+00,    0.0000000000E+00,    1.2463544426E+01,    9.2958469169E-01,    3.2540130761E-01,   -1.7316549879E-01,    1.4161603476E-05,    6.9131111159E+00,    1.2056306183E+04,    1.3396913139E-01,    8.9356814763E+03
        21,    4.5134548408E-03,    0.0000000000E+00,    6.4011067962E-01,    7.2147076469E-01,    6.6696681050E-01,   -1.5242787271E+02,    5.7036335769E+00,    3.7096312818E+02,    3.7015159237E+00,   -9.4638027220E-01,    1.8236787055E-01,   -2.6665772102E-01,    0.0000000000E+00,    0.0000000000E+00,    1.2024075183E+04,    0.0000000000E+00,    0.0000000000E+00
        22,    5.0361674015E-03,    0.0000000000E+00,    6.1292636705E-01,    7.3062520284E-01,    6.5450443221E-01,   -6.4541130117E+00,   -1.3378546638E+02,    2.5898161815E+02,    9.8757381866E+00,   -7.2445582991E-01,   -6.6132747685E-01,    1.9444721356E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1895062136E+04,    0.0000000000E+00,    0.0000000000E+00
        23,    7.6463471457E-04,    0.0000000000E+00,    6.4314771948E-01,    7.2374351171E-01,    6.6087280177E-01,   -1.3739301569E+02,   -5.7264274029E+00,    3.5255161026E+02,    6.0191250383E+01,   -8.7945931068E-01,   -3.5745170460E-01,   -3.1429222030E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1878667946E+04,    0.0000000000E+00,    0.0000000000E+00
        24,    1.6665380505E-03,    0.0000000000E+00,    6.1292491404E-01,    7.3062632554E-01,    6.5450361189E-01,   -1.1164544198E+02,    8.4195389227E+00,    1.7221738527E+02,    1.8423545252E+01,   -1.1946382572E-01,   -8.4924285334E-01,   -5.1431018889E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1742353756E+04,    0.0000000000E+00,    0.0000000000E+00
        25,    1.5331967006E-03,    0.0000000000E+00,    6.1076999128E-01,    7.2859482909E-01,    6.5017493328E-01,   -8.9977595399E+01,   -1.2696651219E+02,    1.6766111355E+02,    3.1584979448E+01,   -6.8350968814E-01,   -6.2261475837E-01,   -3.8100573340E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1546115552E+04,    0.0000000000E+00,    0.0000000000E+00
        26,    6.7984100116E-04,    0.0000000000E+00,    6.1114616838E-01,    7.3114237681E-01,    6.5615548247E-01,   -1.6056302907E+02,   -9.8587124661E+01,    9.6601472214E+01,    2.8109968267E+01,   -7.0340023988E-01,   -5.8062631511E-01,   -4.1000144481E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1469359627E+04,    0.0000000000E+00,    0.0000000000E+00
        27,    9.0750350571E-04,    0.0000000000E+00,    6.1809482075E-01,    7.3090392877E-01,    6.5458794867E-01,   -5.5707404049E+01,    3.5713009905E+00,    2.2318915737E+02,    2.5470197195E+01,   -6.3199029161E-01,   -7.2407891729E-01,   -2.7622091313E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1458781151E+04,    0.0000000000E+00,    0.0000000000E+00
        28,    3.9799421754E-03,    0.0000000000E+00,    6.1304126593E-01,    7.3073625762E-01,    6.5458195808E-01,   -5.4134960126E+01,   -1.0204487544E+02,    2.1658483763E+02,    7.3185820733E+00,   -2.4618244972E-01,   -9.6870780565E-01,    3.1613109837E-02,    0.0000000000E+00,    0.0000000000E+00,    1.1316501820E+04,    0.0000000000E+00,    0.0000000000E+00
        29,    2.0536405841E-01,    0.0000000000E+00,    6.7744299279E-01,    8.0191214659E-01,    6.9215534680E-01,   -2.8623902350E+02,   -4.0131946794E+01,    2.4452296100E+02,    1.1274556661E+00,   -1.3906875009E-01,    7.9848834745E-01,   -5.8572710518E-01,    0.0000000000E+00,    0.0000000000E+00,    1.1254396831E+04,    1.9681630821E-01,    3.4027191526E+03
        30,    4.4167659751E-02,    1.0097497099E-05,    6.4952620524E-01,    6.9526655398E-01,    8.6349343794E-01,    1.1802853901E+01,    9.7228894150E+01,   -6.0464410427E+01,    6.1153931224E+00,    9.9354307651E-01,    9.8285076592E-02,   -5.6676263510E-02,    1.4158125044E-05,    0.0000000000E+00,    7.4282391393E+03,    0.0000000000E+00,    0.0000000000E+00
