### ISSUE TITLE
Sort particles when loading?

### ISSUE THREAD

**Issue by nvaytet** [osyris-project/osyris#67]
Can we sort the particles when they are loaded?
Sort by type or id by default, but provide an option to choose a different key for sorting?

**Comment by nvaytet** [comment]
@haugboel I think providing the option to sort via a different key in the `load()` command would be quite messy.
Would it be ok to sort by default according to `family` or `tag`, and then provide a `.sort` method on the `Datagroup` if you want to sort by something else after loading?

We could also make a config option, so that the default sorting key could be set inside the user's config file?

**Comment by nvaytet** [comment]
On second thought, if we provide a generic sort mechanism on the Datagroup, if you sort the 'amr' group according to say position_x, then the hydro group will be out of sync with the 'amr' group.

Should we have a mechanism that links the amr and hydro groups, or should ensuring synchronization between groups be the user's responsibility?

The linking sounds complicated and brittle...

**Comment by haugboel** [comment]
It is only particles I can think that we would sort. Apart from tags, id and distance to something (to get spherical shells easily) I can’t se other uses, but it would be easy to supply a key and then sorting accordingly.

Sendt fra min iPhone
