### ISSUE TITLE
Rename `xyz` to `position`?

### ISSUE THREAD

**Issue by nvaytet** [osyris-project/osyris#73]
Currently, the position of amr cells and sink particles are named `xyz`.
But this is not a very good name, both in the `Datagroup` and for the figure axes.
(It labels the axes on a map as `xyz_x` and `xyz_y`).

- Should we rename this to `position` to be consistent with the particles `position` field?
- Another option would be to keep them as separate components `x`, `y`, and `z` instead of making them into a vector, but I don't like this as much as it makes it more difficult to re-center the domain with something like `data['amr']['position'] - center` (you would now have to have 3 operations instead)

**Comment by rteyssier** [comment]
I would prefer pos_x for both gas and particle.

**Comment by nvaytet** [comment]
`position` for particles just comes from the `part_file_descriptor` I think?
