### ISSUE TITLE
error when loading a small region

### ISSUE THREAD

**Issue by Lenoble-lab** [osyris-project/osyris#80]
Hi, 
I get this error when I try to load with a limited x range.
I can't manage to see where does it comes from. Do you have any ideas ?

Thanks in advance
Romain Lenoble

My code : 

'''
dx = 200 * osyris.units('pc')
ind = np.argmax(data["hydro"]["density"])
center = data["amr"]["xyz"][ind.values:ind.values+1]
print(center)

data = osyris.Dataset(snap, scale="pc", path=RamsesDir).load(
            select={"hydro": {"Tgas": True, "density": True},
                "amr": {"x": lambda x : np.logical_and(x > center.x - dx, x < center.x + dx)}
        })
''''

The output I get (in a jupyter notebook) : 
'''
'xyz' Min: 1.018e+03 Max: 5.352e+04 [pc] (1, 3)
Processing 64 files in 01/output_00012
 10% : read          0 cells,    1818806 particles
 20% : read          0 cells,    3445178 particles
 31% : read          0 cells,    5303701 particles
 40% : read          0 cells,    6828258 particles
 50% : read       5440 cells,    8263923 particles
 60% : read      39108 cells,   10109265 particles
 70% : read      64386 cells,   11739026 particles
 81% : read      93448 cells,   13579124 particles
 90% : read     112667 cells,   15162271 particles
Loaded: 146843 cells, 16777216 particles.

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_2605110/1392952467.py in <module>
      5 
      6 
----> 7 data = osyris.Dataset(snap, scale="pc", path=RamsesDir).load(
      8             select={"hydro": {"Tgas": True, "density": True},
      9                 "amr": {"x": lambda x : np.logical_and(x > center.x - dx, x < center.x + dx)}

~/anaconda3/lib/python3.9/site-packages/osyris/core/dataset.py in load(self, *args, **kwargs)
     64         for name, group in groups.items():
     65             self[name] = group
---> 66         config.additional_variables(self)
     67         return self
     68 

~/.osyris/config_osyris.py in additional_variables(data)
    120     try:
    121         data['hydro']['mass'] = data['hydro']['density'] * data['amr']['dx']**3
--> 122         data['hydro']['mass'].to('msun')
    123     except KeyError:
    124         pass

~/anaconda3/lib/python3.9/site-packages/osyris/core/array.py in to(self, unit)
    343         else:
    344             new_unit = unit
--> 345         ratio = self._unit.to(new_unit) / new_unit
    346         self._unit = 1.0 * new_unit
    347         self._array *= ratio.magnitude

~/anaconda3/lib/python3.9/site-packages/pint/quantity.py in to(self, other, *contexts, **ctx_kwargs)
    722         other = to_units_container(other, self._REGISTRY)
    723 
--> 724         magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
    725 
    726         return self.__class__(magnitude, other)

~/anaconda3/lib/python3.9/site-packages/pint/quantity.py in _convert_magnitude_not_inplace(self, other, *contexts, **ctx_kwargs)
    671                 return self._REGISTRY.convert(self._magnitude, self._units, other)
    672 
--> 673         return self._REGISTRY.convert(self._magnitude, self._units, other)
    674 
    675     def _convert_magnitude(self, other, *contexts, **ctx_kwargs):

~/anaconda3/lib/python3.9/site-packages/pint/registry.py in convert(self, value, src, dst, inplace)
   1001             return value
   1002 
-> 1003         return self._convert(value, src, dst, inplace)
   1004 
   1005     def _convert(self, value, src, dst, inplace=False, check_dimensionality=True):

~/anaconda3/lib/python3.9/site-packages/pint/registry.py in _convert(self, value, src, dst, inplace)
   1915                 value, src = src._magnitude, src._units
   1916 
-> 1917         return super()._convert(value, src, dst, inplace)
   1918 
   1919     def _get_compatible_units(self, input_units, group_or_system):

~/anaconda3/lib/python3.9/site-packages/pint/registry.py in _convert(self, value, src, dst, inplace)
   1509 
   1510         try:
-> 1511             dst_offset_unit = self._validate_and_extract(dst)
   1512         except ValueError as ex:
   1513             raise DimensionalityError(

~/anaconda3/lib/python3.9/site-packages/pint/registry.py in _validate_and_extract(self, units)
   1434     def _validate_and_extract(self, units):
   1435         # u is for unit, e is for exponent
-> 1436         nonmult_units = [
   1437             (u, e) for u, e in units.items() if not self._is_multiplicative(u)
   1438         ]

~/anaconda3/lib/python3.9/site-packages/pint/registry.py in <listcomp>(.0)
   1435         # u is for unit, e is for exponent
   1436         nonmult_units = [
-> 1437             (u, e) for u, e in units.items() if not self._is_multiplicative(u)
   1438         ]
   1439 

~/anaconda3/lib/python3.9/site-packages/pint/registry.py in _is_multiplicative(self, u)
   1425         # TODO: Might be better to register them.
   1426         names = self.parse_unit_name(u)
-> 1427         assert len(names) == 1
   1428         _, base_name, _ = names[0]
   1429         try:

AssertionError: 

''''

**Comment by Lenoble-lab** [comment]
I don't know if it matter but the simulation I'm trying to load in a cosmological simulation. Could this be a problem with the units?

**Comment by nvaytet** [comment]
The loading seems to happen fine, it seems to be an issue when it is trying to create some additionaly quantities in your configuration file (which is probably just trying the default things?).

Can you paste the contents of your `~/.osyris/config_osyris.py` file?

**Comment by nvaytet** [comment]
In the code you wrote above, you seem to be loading the data twice?
First you load everything, find the center, and then load again a small region around that center?

**Comment by Lenoble-lab** [comment]
Hi, 
Thanks for your answer ! 
Yes I was loading the data twice (that was a test so I can reproduce the tutorial from osyris), to see the source from the error. Do you think it can cause the pb ?

I have removed the ~/.osyris/config_osyris.py (as stated in your tutorial) and then it re-creates it when importing osyris. My file is this one : 

# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2022 Osyris contributors (https://github.com/nvaytet/osyris)
"""
Define default values so that you don't have to specify them every time.
"""
import math
from pint import UnitRegistry

ureg = UnitRegistry(system="cgs")

parameters = {
    'scale': 'au',
    'path': None,
    'select': None,
    'cmap': 'viridis',
    'render_mode': 'pcolormesh'
}


def get_unit(string, ud, ul, ut, scale):

    density = ud * (ureg.g / (ureg.cm**3))
    velocity = (ul / ut) * (ureg.cm / ureg.s)
    magnetic_field = math.sqrt(4.0 * math.pi * ud * (ul / ut)**2) * ureg.G
    momentum = density * velocity
    acceleration = (ul / ut**2) * (ureg.cm / (ureg.s**2))
    energy = ud * ((ul / ut)**2) * (ureg.erg / (ureg.cm**3))
    time = ut * ureg.s
    length = ul * ureg.cm
    mass = density * (length**3)

    scaling = length
    if scale is not None:
        scale = ureg(scale)
        scaling = (length.to(scale) / scale).magnitude * scale

    ramses_units = {
        'density': density,
        'velocity': velocity,
        'velocity_x': velocity,
        'velocity_y': velocity,
        'velocity_z': velocity,
        'momentum': momentum,
        'momentum_x': momentum,
        'momentum_y': momentum,
        'momentum_z': momentum,
        'B_left': magnetic_field,
        'B_left_x': magnetic_field,
        'B_left_y': magnetic_field,
        'B_left_z': magnetic_field,
        'B_right': magnetic_field,
        'B_right_x': magnetic_field,
        'B_right_y': magnetic_field,
        'B_right_z': magnetic_field,
        'B_field': magnetic_field,
        'B_field_x': magnetic_field,
        'B_field_y': magnetic_field,
        'B_field_z': magnetic_field,
        'B_x_left': magnetic_field,
        'B_y_left': magnetic_field,
        'B_z_left': magnetic_field,
        'B_x_right': magnetic_field,
        'B_y_right': magnetic_field,
        'B_z_right': magnetic_field,
        'grav_acceleration': acceleration,
        'grav_acceleration_x': acceleration,
        'grav_acceleration_y': acceleration,
        'grav_acceleration_z': acceleration,
        'thermal_pressure': energy,
        'pressure': energy,
        'radiative_energy': energy,
        'radiative_energy_1': energy,
        'temperature': 1.0 * ureg.K,
        'time': time,
        'x': scaling,
        'y': scaling,
        'z': scaling,
        'xyz_x': scaling,
        'xyz_y': scaling,
        'xyz_z': scaling,
        'position_x': scaling,
        'position_y': scaling,
        'position_z': scaling,
        'dx': scaling,
        'mass': mass
    }

    if string in ramses_units:
        return ramses_units[string]
    else:
        return 1.0 * ureg.dimensionless


def additional_units():
    """
    Define additional useful ureg and constants
    """
    ureg.define('solar_mass = 1.9889e+33 * g = msun')
    ureg.define('radiation_constant = 7.56591469318689378e-015 * erg / cm^3 / K^4 = ar')


def additional_variables(data):
    """
    Here are some additional variables that are to be computed every time data
    is loaded.

    It is recommended to place your variables in a `try/except` block, which
    will prevent errors if the variables are not found, for instance when
    loading data from a different simulation.
    """

    # Magnetic field
    try:
        data['hydro']['B_field'] = 0.5 * (data['hydro']['B_left'] +
                                          data['hydro']['B_right'])
    except KeyError:
        pass

    # Mass
    try:
        data['hydro']['mass'] = data['hydro']['density'] * data['amr']['dx']**3
        data['hydro']['mass'].to('msun')
    except KeyError:
        pass

**Comment by nvaytet** [comment]
I am wondering if you are having issues with what osyris is trying to assume for the units setup, and what you have in your run (maybe it does matter that it is a cosmological run?)

For now, if you want to be able to load the data and play around with it, try to just comment out the line that does
```
data['hydro']['mass'].to('msun')
```
in your config file.
That will hopefully complete the loading.


Now, to try to understand and fix the problem, could you
- paste the contents of your `info_<OUTPUT_NUMBER>.txt` file
- add a `print(data['hydro']['mass'])` in the config file just before you do `data['hydro']['mass'].to('msun')`
- if the output snapshot is not too big, can you share it with me and I can also take a look on my machine

thanks!

**Comment by nvaytet** [comment]
> Yes I was loading the data twice (that was a test so I can reproduce the tutorial from osyris), to see the source from the error. Do you think it can cause the pb ?

1. so the first time you loaded the data, you did not have a problem?
2. Not sure I understand the point of loading the data twice, if you can load the entire snapshot into memory the first time round, why do you want to only upload a small region after that?

**Comment by nvaytet** [comment]
Let me know if you are still having issues or if this can be closed.
